version: "3.8"

services:
  php:
    container_name: laravel
    build: ./docker/php
    tty: false
    networks:
      - default
    ports:
      - ${MY_IP}:${WEB_PORT}:80
    volumes:
      - ${PROJECT_PATH_HOST}:/var/www/html

  mysql:
    container_name: message-board-mysql
    build: ./docker/mysql
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./DBdata:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}